namespace NeutronData.Models
{
    public class DetailRec
    {
        public int Id { get; set; }
        public int CurrentStop { get; set; }
        public int HdrId { get; set; }
        public int Station { get; set; }
        public string Sku { get; set; }
        public int Qty { get; set; }
        public string Des { get; set; }
        public int Multi { get; set; }
        public int SysNum { get; set; }
        public int DbCar1 { get; set; }
        public int DbCar2 { get; set; }
        public int DbCar3 { get; set; }
        public int DbCar4 { get; set; }
        public int DbCar5 { get; set; }
        public int DbCar6 { get; set; }
        public int DbCar7 { get; set; }
        public int DbCar8 { get; set; }
        public int DbCar9 { get; set; }
        public int DbCar10 { get; set; }
        public int DbCar11 { get; set; }
        public int DbCar12 { get; set; }
        public int DbCar13 { get; set; }
        public int DbCar14 { get; set; }
        public int DbCar15 { get; set; }
        public int DbCar16 { get; set; }
        public int DbCar17 { get; set; }
        public int DbCar18 { get; set; }
        public int DbCar19 { get; set; }
        public int DbCar20 { get; set; }
        public int DbCar21 { get; set; }
        public int DbCar22 { get; set; }
        public int DbCar23 { get; set; }
        public int DbCar24 { get; set; }
        public int DbCar25 { get; set; }
        public int DbBin1 { get; set; }
        public int DbBin2 { get; set; }
        public int DbBin3 { get; set; }
        public int DbBin4 { get; set; }
        public int DbBin5 { get; set; }
        public int DbBin6 { get; set; }
        public int DbBin7 { get; set; }
        public int DbBin8 { get; set; }
        public int DbBin9 { get; set; }
        public int DbBin10 { get; set; }
        public int DbBin11 { get; set; }
        public int DbBin12 { get; set; }
        public int DbBin13 { get; set; }
        public int DbBin14 { get; set; }
        public int DbBin15 { get; set; }
        public int DbBin16 { get; set; }
        public int DbBin17 { get; set; }
        public int DbBin18 { get; set; }
        public int DbBin19 { get; set; }
        public int DbBin20 { get; set; }
        public int DbBin21 { get; set; }
        public int DbBin22 { get; set; }
        public int DbBin23 { get; set; }
        public int DbBin24 { get; set; }
        public int DbBin25 { get; set; }
        public int DbLevel1 { get; set; }
        public int DbLevel2 { get; set; }
        public int DbLevel3 { get; set; }
        public int DbLevel4 { get; set; }
        public int DbLevel5 { get; set; }
        public int DbLevel6 { get; set; }
        public int DbLevel7 { get; set; }
        public int DbLevel8 { get; set; }
        public int DbLevel9 { get; set; }
        public int DbLevel10 { get; set; }
        public int DbLevel11 { get; set; }
        public int DbLevel12 { get; set; }
        public int DbLevel13 { get; set; }
        public int DbLevel14 { get; set; }
        public int DbLevel15 { get; set; }
        public int DbLevel16 { get; set; }
        public int DbLevel17 { get; set; }
        public int DbLevel18 { get; set; }
        public int DbLevel19 { get; set; }
        public int DbLevel20 { get; set; }
        public int DbLevel21 { get; set; }
        public int DbLevel22 { get; set; }
        public int DbLevel23 { get; set; }
        public int DbLevel24 { get; set; }
        public int DbLevel25 { get; set; }
        public int DbPart1 { get; set; }
        public int DbPart2 { get; set; }
        public int DbPart3 { get; set; }
        public int DbPart4 { get; set; }
        public int DbPart5 { get; set; }
        public int DbPart6 { get; set; }
        public int DbPart7 { get; set; }
        public int DbPart8 { get; set; }
        public int DbPart9 { get; set; }
        public int DbPart10 { get; set; }
        public int DbPart11 { get; set; }
        public int DbPart12 { get; set; }
        public int DbPart13 { get; set; }
        public int DbPart14 { get; set; }
        public int DbPart15 { get; set; }
        public int DbPart16 { get; set; }
        public int DbPart17 { get; set; }
        public int DbPart18 { get; set; }
        public int DbPart19 { get; set; }
        public int DbPart20 { get; set; }
        public int DbPart21 { get; set; }
        public int DbPart22 { get; set; }
        public int DbPart23 { get; set; }
        public int DbPart24 { get; set; }
        public int DbPart25 { get; set; }
        public int DbSelQty1 { get; set; }
        public int DbSelQty2 { get; set; }
        public int DbSelQty3 { get; set; }
        public int DbSelQty4 { get; set; }
        public int DbSelQty5 { get; set; }
        public int DbSelQty6 { get; set; }
        public int DbSelQty7 { get; set; }
        public int DbSelQty8 { get; set; }
        public int DbSelQty9 { get; set; }
        public int DbSelQty10 { get; set; }
        public int DbSelQty11 { get; set; }
        public int DbSelQty12 { get; set; }
        public int DbSelQty13 { get; set; }
        public int DbSelQty14 { get; set; }
        public int DbSelQty15 { get; set; }
        public int DbSelQty16 { get; set; }
        public int DbSelQty17 { get; set; }
        public int DbSelQty18 { get; set; }
        public int DbSelQty19 { get; set; }
        public int DbSelQty20 { get; set; }
        public int DbSelQty21 { get; set; }
        public int DbSelQty22 { get; set; }
        public int DbSelQty23 { get; set; }
        public int DbSelQty24 { get; set; }
        public int DbSelQty25 { get; set; }
        public int DbOvrFlag1 { get; set; }
        public int DbOvrFlag2 { get; set; }
        public int DbOvrFlag3 { get; set; }
        public int DbOvrFlag4 { get; set; }
        public int DbOvrFlag5 { get; set; }
        public int DbOvrFlag6 { get; set; }
        public int DbOvrFlag7 { get; set; }
        public int DbOvrFlag8 { get; set; }
        public int DbOvrFlag9 { get; set; }
        public int DbOvrFlag10 { get; set; }
        public int DbOvrFlag11 { get; set; }
        public int DbOvrFlag12 { get; set; }
        public int DbOvrFlag13 { get; set; }
        public int DbOvrFlag14 { get; set; }
        public int DbOvrFlag15 { get; set; }
        public int DbOvrFlag16 { get; set; }
        public int DbOvrFlag17 { get; set; }
        public int DbOvrFlag18 { get; set; }
        public int DbOvrFlag19 { get; set; }
        public int DbOvrFlag20 { get; set; }
        public int DbOvrFlag21 { get; set; }
        public int DbOvrFlag22 { get; set; }
        public int DbOvrFlag23 { get; set; }
        public int DbOvrFlag24 { get; set; }
        public int DbOvrFlag25 { get; set; }
        public int DbOvrQty1 { get; set; }
        public int DbOvrQty2 { get; set; }
        public int DbOvrQty3 { get; set; }
        public int DbOvrQty4 { get; set; }
        public int DbOvrQty5 { get; set; }
        public int DbOvrQty6 { get; set; }
        public int DbOvrQty7 { get; set; }
        public int DbOvrQty8 { get; set; }
        public int DbOvrQty9 { get; set; }
        public int DbOvrQty10 { get; set; }
        public int DbOvrQty11 { get; set; }
        public int DbOvrQty12 { get; set; }
        public int DbOvrQty13 { get; set; }
        public int DbOvrQty14 { get; set; }
        public int DbOvrQty15 { get; set; }
        public int DbOvrQty16 { get; set; }
        public int DbOvrQty17 { get; set; }
        public int DbOvrQty18 { get; set; }
        public int DbOvrQty19 { get; set; }
        public int DbOvrQty20 { get; set; }
        public int DbOvrQty21 { get; set; }
        public int DbOvrQty22 { get; set; }
        public int DbOvrQty23 { get; set; }
        public int DbOvrQty24 { get; set; }
        public int DbOvrQty25 { get; set; }
        public int PickStep { get; set; }
        public int OcQty { get; set; }
        public int OffCar { get; set; }
        public int OcTrig { get; set; }
        public string OcSlot1 { get; set; }
        public string OcSlot2 { get; set; }
        public string OcSlot3 { get; set; }
        public string OcSlot4 { get; set; }
        public string OcSlot5 { get; set; }
        public string OcSlot6 { get; set; }
        public string OcSlot7 { get; set; }
        public string OcSlot8 { get; set; }
        public string OcSlot9 { get; set; }
        public string OcSlot10 { get; set; }
        public string OcSlot11 { get; set; }
        public string OcSlot12 { get; set; }
        public string OcSlot13 { get; set; }
        public string OcSlot14 { get; set; }
        public string OcSlot15 { get; set; }
        public string OcSlot16 { get; set; }
        public string OcSlot17 { get; set; }
        public string OcSlot18 { get; set; }
        public string OcSlot19 { get; set; }
        public string OcSlot20 { get; set; }
        public string OcSlot21 { get; set; }
        public string OcSlot22 { get; set; }
        public string OcSlot23 { get; set; }
        public string OcSlot24 { get; set; }
        public string OcSlot25 { get; set; }
        public string OcRcvDate1 { get; set; }
        public string OcRcvDate2 { get; set; }
        public string OcRcvDate3 { get; set; }
        public string OcRcvDate4 { get; set; }
        public string OcRcvDate5 { get; set; }
        public string OcRcvDate6 { get; set; }
        public string OcRcvDate7 { get; set; }
        public string OcRcvDate8 { get; set; }
        public string OcRcvDate9 { get; set; }
        public string OcRcvDate10 { get; set; }
        public string OcRcvDate11 { get; set; }
        public string OcRcvDate12 { get; set; }
        public string OcRcvDate13 { get; set; }
        public string OcRcvDate14 { get; set; }
        public string OcRcvDate15 { get; set; }
        public string OcRcvDate16 { get; set; }
        public string OcRcvDate17 { get; set; }
        public string OcRcvDate18 { get; set; }
        public string OcRcvDate19 { get; set; }
        public string OcRcvDate20 { get; set; }
        public string OcRcvDate21 { get; set; }
        public string OcRcvDate22 { get; set; }
        public string OcRcvDate23 { get; set; }
        public string OcRcvDate24 { get; set; }
        public string OcRcvDate25 { get; set; }
        public int OcSelQty1 { get; set; }
        public int OcSelQty2 { get; set; }
        public int OcSelQty3 { get; set; }
        public int OcSelQty4 { get; set; }
        public int OcSelQty5 { get; set; }
        public int OcSelQty6 { get; set; }
        public int OcSelQty7 { get; set; }
        public int OcSelQty8 { get; set; }
        public int OcSelQty9 { get; set; }
        public int OcSelQty10 { get; set; }
        public int OcSelQty11 { get; set; }
        public int OcSelQty12 { get; set; }
        public int OcSelQty13 { get; set; }
        public int OcSelQty14 { get; set; }
        public int OcSelQty15 { get; set; }
        public int OcSelQty16 { get; set; }
        public int OcSelQty17 { get; set; }
        public int OcSelQty18 { get; set; }
        public int OcSelQty19 { get; set; }
        public int OcSelQty20 { get; set; }
        public int OcSelQty21 { get; set; }
        public int OcSelQty22 { get; set; }
        public int OcSelQty23 { get; set; }
        public int OcSelQty24 { get; set; }
        public int OcSelQty25 { get; set; }
        public int OcOvrFlag1 { get; set; }
        public int OcOvrFlag2 { get; set; }
        public int OcOvrFlag3 { get; set; }
        public int OcOvrFlag4 { get; set; }
        public int OcOvrFlag5 { get; set; }
        public int OcOvrFlag6 { get; set; }
        public int OcOvrFlag7 { get; set; }
        public int OcOvrFlag8 { get; set; }
        public int OcOvrFlag9 { get; set; }
        public int OcOvrFlag10 { get; set; }
        public int OcOvrFlag11 { get; set; }
        public int OcOvrFlag12 { get; set; }
        public int OcOvrFlag13 { get; set; }
        public int OcOvrFlag14 { get; set; }
        public int OcOvrFlag15 { get; set; }
        public int OcOvrFlag16 { get; set; }
        public int OcOvrFlag17 { get; set; }
        public int OcOvrFlag18 { get; set; }
        public int OcOvrFlag19 { get; set; }
        public int OcOvrFlag20 { get; set; }
        public int OcOvrFlag21 { get; set; }
        public int OcOvrFlag22 { get; set; }
        public int OcOvrFlag23 { get; set; }
        public int OcOvrFlag24 { get; set; }
        public int OcOvrFlag25 { get; set; }
        public int OcOvrQty1 { get; set; }
        public int OcOvrQty2 { get; set; }
        public int OcOvrQty3 { get; set; }
        public int OcOvrQty4 { get; set; }
        public int OcOvrQty5 { get; set; }
        public int OcOvrQty6 { get; set; }
        public int OcOvrQty7 { get; set; }
        public int OcOvrQty8 { get; set; }
        public int OcOvrQty9 { get; set; }
        public int OcOvrQty10 { get; set; }
        public int OcOvrQty11 { get; set; }
        public int OcOvrQty12 { get; set; }
        public int OcOvrQty13 { get; set; }
        public int OcOvrQty14 { get; set; }
        public int OcOvrQty15 { get; set; }
        public int OcOvrQty16 { get; set; }
        public int OcOvrQty17 { get; set; }
        public int OcOvrQty18 { get; set; }
        public int OcOvrQty19 { get; set; }
        public int OcOvrQty20 { get; set; }
        public int OcOvrQty21 { get; set; }
        public int OcOvrQty22 { get; set; }
        public int OcOvrQty23 { get; set; }
        public int OcOvrQty24 { get; set; }
        public int OcOvrQty25 { get; set; }
        public int ToteNumber { get; set; }
        public string UnitOfIssue { get; set; }
        public int OcPicked { get; set; }
        public string PickSeq { get; set; }
        public string SerialNum { get; set; }
        public int OcPending { get; set; }
        public string CCClass { get; set; }
        public string OcOrgZone { get; set; }
        public string OcOvrZone { get; set; }
        //DetUserType
        public string UserArea { get; set; }

    }
}
