using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NeutronData.Models
{
    public class OrdSummRec
    {
        public int Id { get; set; }
        public int HdrId { get; set; }
        public int Station { get; set; }
        public string Order { get; set; }
        public int OcPcs { get; set; }
        public string Status { get; set; }
        public string OcStatus1 { get; set; }
        public string OcStatus2 { get; set; }
        public string OcStatus3 { get; set; }
        public string OcStatus4 { get; set; }
        public string OcStatus5 { get; set; }
        public string OcStatus6 { get; set; }
        public string OcStatus7 { get; set; }
        public string OcStatus8 { get; set; }
        public string OcStatus9 { get; set; }
        public string OcStatus10 { get; set; }
        public string OcStatus11 { get; set; }
        public string OcStatus12 { get; set; }
        public string OcStatus13 { get; set; }
        public string OcStatus14 { get; set; }
        public string OcStatus15 { get; set; }
        public string OcStatus16 { get; set; }
        public string OcStatus17 { get; set; }
        public string OcStatus18 { get; set; }
        public string OcStatus19 { get; set; }
        public string OcStatus20 { get; set; }
        public string OcStatus21 { get; set; }
        public string OcStatus22 { get; set; }
        public string OcStatus23 { get; set; }
        public string OcStatus24 { get; set; }
        public string OcStatus25 { get; set; }
        public string OcStatus26 { get; set; }
        public string OcStatus27 { get; set; }
        public string OcStatus28 { get; set; }
        public string OcStatus29 { get; set; }
        public string OcStatus30 { get; set; }
        public string OcStatus31 { get; set; }
        public string OcStatus32 { get; set; }
        public string OcStatus33 { get; set; }
        public string OcStatus34 { get; set; }
        public string OcStatus35 { get; set; }
        public string OcStatus36 { get; set; }
        public string OcStatus37 { get; set; }
        public int OcOrderLock1 { get; set; }
        public int OcOrderLock2 { get; set; }
        public int OcOrderLock3 { get; set; }
        public int OcOrderLock4 { get; set; }
        public int OcOrderLock5 { get; set; }
        public int OcOrderLock6 { get; set; }
        public int OcOrderLock7 { get; set; }
        public int OcOrderLock8 { get; set; }
        public int OcOrderLock9 { get; set; }
        public int OcOrderLock10 { get; set; }
        public int OcOrderLock11 { get; set; }
        public int OcOrderLock12 { get; set; }
        public int OcOrderLock13 { get; set; }
        public int OcOrderLock14 { get; set; }
        public int OcOrderLock15 { get; set; }
        public int OcOrderLock16 { get; set; }
        public int OcOrderLock17 { get; set; }
        public int OcOrderLock18 { get; set; }
        public int OcOrderLock19 { get; set; }
        public int OcOrderLock20 { get; set; }
        public int OcOrderLock21 { get; set; }
        public int OcOrderLock22 { get; set; }
        public int OcOrderLock23 { get; set; }
        public int OcOrderLock24 { get; set; }
        public int OcOrderLock25 { get; set; }
        public int OcOrderLock26 { get; set; }
        public int OcOrderLock27 { get; set; }
        public int OcOrderLock28 { get; set; }
        public int OcOrderLock29 { get; set; }
        public int OcOrderLock30 { get; set; }
        public int OcOrderLock31 { get; set; }
        public int OcOrderLock32 { get; set; }
        public int OcOrderLock33 { get; set; }
        public int OcOrderLock34 { get; set; }
        public int OcOrderLock35 { get; set; }
        public int OcOrderLock36 { get; set; }
        public int OcOrderLock37 { get; set; }
        public string OcPrtStat { get; set; }
        public int Priority { get; set; }
        public int Staging { get; set; }
        public string BatchClass { get; set; }
        public string Invoice { get; set; }
        public string LoadDate { get; set; }
        public string LoadTime { get; set; }
        public int BegRec { get; set; }
        public int EndRec { get; set; }
        public int Suspend { get; set; }
        public int pcs { get; set; }
        public string PickDate { get; set; }
        public string PickBeg { get; set; }
        public string PickEmp { get; set; }
        public int OffCar { get; set; }
        public int Manifest { get; set; }
        public string Batched { get; set; }
        public string ReplSeq { get; set; }
        public string PickEnd { get; set; }
        public string MarshCode { get; set; }
        public int CurrentTote { get; set; }
        public int CurrentPcs { get; set; }
        public int AverageTote { get; set; }
        public int TotalTotes { get; set; }
        public int EndOfOrder { get; set; }
        public Single ET { get; set; }
        public int RFLabels { get; set; }
        public int RFLabPrt { get; set; }
        public int RFManifest { get; set; }
        public int OCLines { get; set; }
        public int RfLabPos { get; set; }
        public int SingleOrder { get; set; }
        public string OcPickEmp1 { get; set; }
        public string OcPickEmp2 { get; set; }
        public string OcPickEmp3 { get; set; }
        public string OcPickEmp4 { get; set; }
        public string OcPickEmp5 { get; set; }
        public string OcPickEmp6 { get; set; }
        public string OcPickEmp7 { get; set; }
        public string OcPickEmp8 { get; set; }
        public string OcPickEmp9 { get; set; }
        public string OcPickEmp10 { get; set; }
        public string OcPickEmp11 { get; set; }
        public string OcPickEmp12 { get; set; }
        public string OcPickEmp13 { get; set; }
        public string OcPickEmp14 { get; set; }
        public string OcPickEmp15 { get; set; }
        public string OcPickEmp16 { get; set; }
        public string OcPickEmp17 { get; set; }
        public string OcPickEmp18 { get; set; }
        public string OcPickEmp19 { get; set; }
        public string OcPickEmp20 { get; set; }
        public string OcPickEmp21 { get; set; }
        public string OcPickEmp22 { get; set; }
        public string OcPickEmp23 { get; set; }
        public string OcPickEmp24 { get; set; }
        public string OcPickEmp25 { get; set; }
        public string OcPickEmp26 { get; set; }
        public string OcPickEmp27 { get; set; }
        public string OcPickEmp28 { get; set; }
        public string OcPickEmp29 { get; set; }
        public string OcPickEmp30 { get; set; }
        public string OcPickEmp31 { get; set; }
        public string OcPickEmp32 { get; set; }
        public string OcPickEmp33 { get; set; }
        public string OcPickEmp34 { get; set; }
        public string OcPickEmp35 { get; set; }
        public string OcPickEmp36 { get; set; }
        public string OcPickEmp37 { get; set; }
        public int ZoneOcPcs1 { get; set; }
        public int ZoneOcPcs2 { get; set; }
        public int ZoneOcPcs3 { get; set; }
        public int ZoneOcPcs4 { get; set; }
        public int ZoneOcPcs5 { get; set; }
        public int ZoneOcPcs6 { get; set; }
        public int ZoneOcPcs7 { get; set; }
        public int ZoneOcPcs8 { get; set; }
        public int ZoneOcPcs9 { get; set; }
        public int ZoneOcPcs10 { get; set; }
        public int ZoneOcPcs11 { get; set; }
        public int ZoneOcPcs12 { get; set; }
        public int ZoneOcPcs13 { get; set; }
        public int ZoneOcPcs14 { get; set; }
        public int ZoneOcPcs15 { get; set; }
        public int ZoneOcPcs16 { get; set; }
        public int ZoneOcPcs17 { get; set; }
        public int ZoneOcPcs18 { get; set; }
        public int ZoneOcPcs19 { get; set; }
        public int ZoneOcPcs20 { get; set; }
        public int ZoneOcPcs21 { get; set; }
        public int ZoneOcPcs22 { get; set; }
        public int ZoneOcPcs23 { get; set; }
        public int ZoneOcPcs24 { get; set; }
        public int ZoneOcPcs25 { get; set; }
        public int ZoneOcPcs26 { get; set; }
        public int ZoneOcPcs27 { get; set; }
        public int ZoneOcPcs28 { get; set; }
        public int ZoneOcPcs29 { get; set; }
        public int ZoneOcPcs30 { get; set; }
        public int ZoneOcPcs31 { get; set; }
        public int ZoneOcPcs32 { get; set; }
        public int ZoneOcPcs33 { get; set; }
        public int ZoneOcPcs34 { get; set; }
        public int ZoneOcPcs35 { get; set; }
        public int ZoneOcPcs36 { get; set; }
        public int ZoneOcPcs37 { get; set; }
        public int ZoneOcLines1 { get; set; }
        public int ZoneOcLines2 { get; set; }
        public int ZoneOcLines3 { get; set; }
        public int ZoneOcLines4 { get; set; }
        public int ZoneOcLines5 { get; set; }
        public int ZoneOcLines6 { get; set; }
        public int ZoneOcLines7 { get; set; }
        public int ZoneOcLines8 { get; set; }
        public int ZoneOcLines9 { get; set; }
        public int ZoneOcLines10 { get; set; }
        public int ZoneOcLines11 { get; set; }
        public int ZoneOcLines12 { get; set; }
        public int ZoneOcLines13 { get; set; }
        public int ZoneOcLines14 { get; set; }
        public int ZoneOcLines15 { get; set; }
        public int ZoneOcLines16 { get; set; }
        public int ZoneOcLines17 { get; set; }
        public int ZoneOcLines18 { get; set; }
        public int ZoneOcLines19 { get; set; }
        public int ZoneOcLines20 { get; set; }
        public int ZoneOcLines21 { get; set; }
        public int ZoneOcLines22 { get; set; }
        public int ZoneOcLines23 { get; set; }
        public int ZoneOcLines24 { get; set; }
        public int ZoneOcLines25 { get; set; }
        public int ZoneOcLines26 { get; set; }
        public int ZoneOcLines27 { get; set; }
        public int ZoneOcLines28 { get; set; }
        public int ZoneOcLines29 { get; set; }
        public int ZoneOcLines30 { get; set; }
        public int ZoneOcLines31 { get; set; }
        public int ZoneOcLines32 { get; set; }
        public int ZoneOcLines33 { get; set; }
        public int ZoneOcLines34 { get; set; }
        public int ZoneOcLines35 { get; set; }
        public int ZoneOcLines36 { get; set; }
        public int ZoneOcLines37 { get; set; }
        public int CrossDock { get; set; }
        public string ToteNumber1 { get; set; }
        public string ToteNumber2 { get; set; }
        public string ToteNumber3 { get; set; }
        public string ToteNumber4 { get; set; }
        public string ToteNumber5 { get; set; }
        public string ToteNumber6 { get; set; }
        public string ToteNumber7 { get; set; }
        public string ToteNumber8 { get; set; }
        public string ToteNumber9 { get; set; }
        public string ToteNumber10 { get; set; }
        public string ToteNumber11 { get; set; }
        public string ToteNumber12 { get; set; }
        public string ToteNumber13 { get; set; }
        public string ToteNumber14 { get; set; }
        public string ToteNumber15 { get; set; }
        public string ToteNumber16 { get; set; }
        public string ToteNumber17 { get; set; }
        public string ToteNumber18 { get; set; }
        public string ToteNumber19 { get; set; }
        public string ToteNumber20 { get; set; }
        public int CarLines { get; set; }
        public int MaintainEntrySeq { get; set; }
        public byte PriFlag { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
    }
}
